// Auto-generated by build-catalogue.ts — do not edit
const CATALOGUE = {
  "apis": [
    {
      "slug": "conclusions-entretiens",
      "title": "Conclusions Entretiens",
      "version": "1.0.0",
      "description": "Ce service permet de récupérer les données concernant les entretiens réalisés par un usager. Scope : api_conclusions-entretiensv1, conclusionsentretienagent Royaume : /agent",
      "baseUrl": "api.francetravail.io/partenaire/conclusions-entretiens/v1",
      "auth": "agent",
      "endpointCount": 1,
      "schemaCount": 1,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "GET",
          "path": "/entretiens",
          "summary": "Liste les conclusions d'entretiens d'un usager"
        }
      ],
      "schemas": [
        "ConclusionEntretienPartenaireDetailsDto"
      ],
      "pageId": 515,
      "hasDocPage": true,
      "concepts": [
        "Entretien — type et date",
        "Modalité de contact",
        "Conseiller et agence"
      ],
      "starred": false
    },
    {
      "slug": "diagnostic-usager",
      "title": "Diagnostic Usager",
      "version": "4.0",
      "description": "A partir de la saisie d’un jeton usager fourni par l’API « recherche usager », ce service permet de restituer et mettre à jour les données propres aux diagnostics d’un demandeur d’emploi. L'API diagnostic usager permet de consulter les données relatives au diagnostic socio-professionnel : - Besoins…",
      "baseUrl": "api.francetravail.io/partenaire/diagnosticargumente/v4",
      "auth": "agent",
      "endpointCount": 25,
      "schemaCount": 49,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "GET",
          "path": "/dossiers",
          "summary": "Récupère le dossier agrégé de l'usager"
        },
        {
          "method": "POST",
          "path": "/dossiers",
          "summary": "Enregistre le dossier agrégé de l'usager"
        },
        {
          "method": "GET",
          "path": "/autonomienumerique",
          "summary": "Récupère l'autonomie numérique de l'usager"
        },
        {
          "method": "POST",
          "path": "/autonomienumerique",
          "summary": "Enregistre les modifications de l'autonomie numérique de l'usager"
        },
        {
          "method": "GET",
          "path": "/besoins",
          "summary": "Récupère les besoins de l'usager"
        },
        {
          "method": "GET",
          "path": "/contraintes",
          "summary": "Récupère les contraintes de l'usager"
        },
        {
          "method": "POST",
          "path": "/contraintes",
          "summary": "Enregistre les modifications de contraintes de l'usager"
        },
        {
          "method": "GET",
          "path": "/diagnostics",
          "summary": "Récupère les diagnostics de l'usager"
        },
        {
          "method": "POST",
          "path": "/diagnostics",
          "summary": "Enregistre la création d'un diagnostic de l'usager"
        },
        {
          "method": "PUT",
          "path": "/diagnostics/{idDiagnostic}",
          "summary": "Enregistre les modifications d'un diagnostic de l'usager"
        },
        {
          "method": "POST",
          "path": "/diagnostics/{idDiagnostic}/besoins",
          "summary": "Enregistre les modifications de Besoins de l'usager"
        },
        {
          "method": "POST",
          "path": "/diagnostics/{idDiagnostic}/priorise",
          "summary": "Priorise le diagnostic de l'usager"
        },
        {
          "method": "POST",
          "path": "/diagnostics/{idDiagnostic}/supprime",
          "summary": "Supprime le diagnostic de l'usager"
        },
        {
          "method": "GET",
          "path": "/dossiers/historisation",
          "summary": "Récupère les données historisées du dossier de l'usager"
        },
        {
          "method": "GET",
          "path": "/historisation/autonomienumerique",
          "summary": "Récupère les données historisées de l'autonomie numérique de l'usager"
        },
        {
          "method": "GET",
          "path": "/historisation/contraintes",
          "summary": "Récupère les données historisées des contraintes de l'usager"
        },
        {
          "method": "GET",
          "path": "/historisation/diagnostics",
          "summary": "Récupère les données historisées des diagnostics de l'usager"
        },
        {
          "method": "GET",
          "path": "/historisation/diagnostics/{idDiagnostic}/besoins",
          "summary": "Récupère les données historisées des besoins de l'usager"
        },
        {
          "method": "GET",
          "path": "/historisation/pouvoiragir",
          "summary": "Récupère les données historisées du pouvoir d'agir de l'usager"
        },
        {
          "method": "GET",
          "path": "/pouvoiragir",
          "summary": "Récupère les données du pouvoir d'agir de l'usager"
        },
        {
          "method": "POST",
          "path": "/pouvoiragir",
          "summary": "Enregistre les modifications du pouvoir d'agir de l'usager"
        },
        {
          "method": "GET",
          "path": "/referentiel",
          "summary": "Récupère l'ensemble des données du référentiel pour le diagnostic"
        },
        {
          "method": "GET",
          "path": "/referentiel/pouvoir-agir/analyse",
          "summary": "Récupère le référentiel des analyses du pouvoir d'agir"
        },
        {
          "method": "GET",
          "path": "/referentiel/{domaine}",
          "summary": "Récupère les données du référentiel, restreint à un domaine"
        },
        {
          "method": "GET",
          "path": "/referentiel/{domaine}/{sous-domaine}",
          "summary": "Récupère les données du référentiel, restreint au domaine et sous-domaine"
        }
      ],
      "schemas": [
        "DossierIndividuDto",
        "AutonomieNumeriqueIndividuDto",
        "AgentDto",
        "BesoinIndividuDto",
        "ContrainteIndividuDto",
        "ObjectifDto",
        "SituationDto",
        "BesoinsParDiagnosticIndividuDto",
        "DiagnosticIndividuDto",
        "ThematiqueBesoinDto",
        "PouvoirAgirIndividuDto",
        "ThematiqueContrainte",
        "EnregistrerDossierDto",
        "EnregistrerAutonomieNumeriqueDto",
        "BesoinEnregistrerDto",
        "ContrainteEnregistrerDto",
        "EnregistrerBesoinsDto",
        "EnregistrerContraintesDto",
        "ObjectifEnregistrerDto",
        "SituationEnregistrerDto",
        "EnregistrerDiagnosticPourDossierDto",
        "EnregistrerPouvoirAgirDto",
        "DiagnosticsIndividusDto",
        "EnregistrerDiagnosticDto",
        "DossierIndividuHistorisationDto",
        "AutonomieNumeriqueHistorisationDto",
        "BesoinIndividuHistorisationDto",
        "ContrainteHistorisationDto",
        "ObjectifHistorisationDto",
        "SituationHistorisationDto",
        "BesoinsIndividuHistorisationDto",
        "ContraintesIndividuHistorisationDto",
        "DiagnosticsIndividuHistorisationDto",
        "DiagnosticIndividuHistorisationDto",
        "PouvoirAgirIndividuHistorisationDto",
        "VersionExploration",
        "DeclareSansContrainteIndividuDto",
        "ReponseEnregistrerDiagnosticDto",
        "DonneesReferentielDto",
        "ThematiqueBesoinDto1",
        "ThematiqueContrainteDto",
        "PouvoirAgirDto",
        "AideQuestionnementDto",
        "BesoinDto",
        "ContrainteDto",
        "QuestionDto",
        "AnalyseDto",
        "SituationDto1",
        "ObjectifDto1"
      ],
      "pageId": 477,
      "hasDocPage": true,
      "concepts": [
        "Projets professionnels et besoins",
        "Contraintes personnelles",
        "Confiance et capacité à agir",
        "Maîtrise du numérique"
      ],
      "starred": true
    },
    {
      "slug": "informations-administratives-usager",
      "title": "Informations administratives usager",
      "version": "1.2.0",
      "description": "Cette API permet de récupérer les données d'un usager (état civil, adresses, email, téléphones et numéro France Travail)  Scopes : api_informations-administrativesv1,informationsadministrativesusager,profil_accedant   Royaume : /agent",
      "baseUrl": "api.francetravail.io/partenaire/informations-administratives/v1",
      "auth": "agent",
      "endpointCount": 1,
      "schemaCount": 6,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "GET",
          "path": "/usager",
          "summary": "Récupère l'état civil et les coordonnées d'un usager"
        }
      ],
      "schemas": [
        "UsagerResource",
        "AdresseResource",
        "EmailResource",
        "EtatCivilResource",
        "TelephoneResource",
        "DonneesErreur"
      ],
      "pageId": 449,
      "hasDocPage": true,
      "concepts": [
        "État civil",
        "Adresses",
        "Coordonnées de contact"
      ],
      "starred": false
    },
    {
      "slug": "metiers-recherches-projets-evolution",
      "title": "Métiers recherchés, projets d'évolution et projets de création, reprise et franchise d'entreprise",
      "version": "1.0.40",
      "description": "Cette API permet de récupérer : - la liste des métiers recherchés par l'usager, - les projets d'évolution professionnelle souhaités par l'usager - et les projets de création, reprise ou franchise d'entreprise de l'usager    Les données retournées proviennent du profil de compétences de l'usager au…",
      "baseUrl": "api.francetravail.io/partenaire/metiers-projets-entreprises/v2",
      "auth": "agent",
      "endpointCount": 2,
      "schemaCount": 17,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "GET",
          "path": "/metiers-recherches",
          "summary": "Récupérer les métiers recherchés et projets d'évolution professionnelle"
        },
        {
          "method": "GET",
          "path": "/projets-cref",
          "summary": "Récupérer les projets de création, reprise et franchise d'entreprise"
        }
      ],
      "schemas": [
        "appellation",
        "contrat",
        "dureeExperience",
        "dureeHebdomadaire",
        "lieu",
        "metierRecherche",
        "mobilite",
        "mobiliteHabitation",
        "projetCref",
        "rome",
        "salaire",
        "typeContrat",
        "typeLieu",
        "typologieEmploi",
        "uniteDureeExperience",
        "uniteLieu",
        "uniteTempsTravail"
      ],
      "pageId": 452,
      "hasDocPage": true,
      "concepts": [
        "Métier ciblé",
        "Conditions souhaitées",
        "Mobilité géographique",
        "Projet entrepreneurial"
      ],
      "starred": false
    },
    {
      "slug": "orientation-usager",
      "title": "Orientation Usager",
      "version": "1.0",
      "description": "Cette API permet : - de récupérer une proposition de résultat d'orientation d'un usager. - de prendre une décision afin de l'orienter vers un organisme et dans un des trois parcours : Social, Socio-Professionnel, Professionnel. - d'orienter un usager sans avoir à détailler les critères de…",
      "baseUrl": "api.francetravail.io/partenaire/orientationusager/v1",
      "auth": "agent",
      "endpointCount": 5,
      "schemaCount": 14,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "POST",
          "path": "/calculOrientation",
          "summary": "Calculer une orientation"
        },
        {
          "method": "GET",
          "path": "/lectureOrientation",
          "summary": "Lire les orientations"
        },
        {
          "method": "POST",
          "path": "/orientation",
          "summary": "Orienter un usager"
        },
        {
          "method": "PUT",
          "path": "/modificationOrientation",
          "summary": "Modifier le parcours et/ou la structure"
        },
        {
          "method": "POST",
          "path": "/decisionOrientation",
          "summary": "Décider une orientation"
        }
      ],
      "schemas": [
        "OrientationCA",
        "CriteresOrientationCA_CalculerEntree",
        "OrientationCA_Calculer",
        "Structure",
        "StructureDecision",
        "CriteresOrientationCA_Calculer",
        "Adresse",
        "OrientationCA_Lecture",
        "Structure_Lecture",
        "CriteresOrientationCA_Lecture",
        "DecisionCA_Lecture",
        "OrientationCreationCA_Commun",
        "Structure_Commun",
        "DecisionCA"
      ],
      "pageId": null,
      "hasDocPage": true,
      "concepts": [
        "Calcul d'orientation",
        "Décision d'orientation",
        "Parcours et structure",
        "Critères sociaux et professionnels"
      ],
      "starred": true
    },
    {
      "slug": "rechercher-usager",
      "title": "Rechercher usager",
      "version": "2.0",
      "description": "Ce service permet de rechercher un usager connu du réseau pour l'emploi en fonction de critères discriminants et le cas échéant de récupérer un jeton usager ainsi que le numéro France Travail permettant d'accéder à d'autres API Scope : api_rechercher-usagerv2,rechercheusager,profil_accedant Royaume…",
      "baseUrl": "api.francetravail.io/partenaire/rechercher-usager/v2",
      "auth": "agent",
      "endpointCount": 2,
      "schemaCount": 7,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "POST",
          "path": "/usagers/par-datenaissance-et-nir",
          "summary": "Rechercher un usager par date de naissance et numéro de sécurité sociale (NIR)"
        },
        {
          "method": "POST",
          "path": "/usagers/par-numero-francetravail",
          "summary": "Rechercher un usager par numéro France Travail"
        }
      ],
      "schemas": [
        "ParDateNaissanceEtNirDTO",
        "ResultatDTO",
        "Resultat400DTO",
        "Resultat403DTO",
        "Resultat500DTO",
        "Resultat503DTO",
        "ParNumeroFTDTO"
      ],
      "pageId": 465,
      "hasDocPage": true,
      "concepts": [
        "Identification de l'agent",
        "Recherche par NIR + date de naissance",
        "Recherche par numéro France Travail"
      ],
      "starred": false
    },
    {
      "slug": "rendez-vous-partenaires",
      "title": "Rendez-vous partenaire",
      "version": "1.0.0",
      "description": "L'API Rendez-vous partenaire contient des données sur les rendez-vous d'un usager. Grâce à ses différentes ressources, l'API permet pour un usager donné de : - Créer un rendez-vous usager dans le système d'information France Travail.  - Modifier un rendez-vous préalablement créé dans le système…",
      "baseUrl": "api.francetravail.io/partenaire/rendez-vous-partenaire/v1",
      "auth": "agent",
      "endpointCount": 4,
      "schemaCount": 9,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "POST",
          "path": "/rendez-vous",
          "summary": "Créer un rendez-vous usager"
        },
        {
          "method": "PUT",
          "path": "/rendez-vous",
          "summary": "Modifier un rendez-vous usager"
        },
        {
          "method": "GET",
          "path": "/rendez-vous-usager",
          "summary": "Retourner la liste des rendez-vous de l'usager"
        },
        {
          "method": "DELETE",
          "path": "/rendez-vous/{id}",
          "summary": "Annuler un rendez-vous usager"
        }
      ],
      "schemas": [
        "Interlocuteur",
        "Organisme",
        "RendezVousPartenaire",
        "ReponseDepotRdvp",
        "AdresseRDVU",
        "HistoriqueEvenementRDVU",
        "InterlocuteurRDVU",
        "OrganismeRDVU",
        "RendezVousUsager"
      ],
      "pageId": 416,
      "hasDocPage": true,
      "concepts": [
        "Lecture — agenda complet",
        "Écriture — RDV du partenaire"
      ],
      "starred": true
    },
    {
      "slug": "statut-usager",
      "title": "Statut Usager",
      "version": "2.0",
      "description": "Cette API permet de restituer le statut, la durée, le motif et la catégorie d’inscription ainsi que la situation au regard de l’emploi de l’usager",
      "baseUrl": "api.francetravail.io/partenaire/contrat-usager/v2",
      "auth": "agent",
      "endpointCount": 1,
      "schemaCount": 2,
      "group": "usager-agent",
      "groupLabel": "Dossier usager",
      "endpoints": [
        {
          "method": "GET",
          "path": "/contrat",
          "summary": "Récupère les données du contrat d'un usager"
        }
      ],
      "schemas": [
        "ContratResponse",
        "Contrat"
      ],
      "pageId": 466,
      "hasDocPage": true,
      "concepts": [
        "Statut d'inscription",
        "Durée d'inscription",
        "Motif et catégorie",
        "Situation et clôture"
      ],
      "starred": false
    },
    {
      "slug": "ajout-competence",
      "title": "API Ajout de Compétence",
      "version": "1.0.0",
      "description": "Cette API permet d'enregistrer des compétences dans le portefeuille de compétences.",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-gestion-profilcompetences/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 0,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "POST",
          "path": "/competences/enregistrer",
          "summary": "Enregistrer des compétences"
        }
      ],
      "schemas": [],
      "pageId": 320,
      "hasDocPage": true,
      "concepts": [
        "Compétences ROME à enregistrer",
        "Réponse partielle (206)"
      ],
      "starred": false
    },
    {
      "slug": "coordonnees",
      "title": "API Coordonnées",
      "version": "1.0",
      "description": "L'API Coordonnées permet de restituer l'adresse postale de l'utilisateur connecté à votre application.",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-coordonnees/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 1,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/coordonnees",
          "summary": "Récupérer les coordonnées de l'utilisateur"
        }
      ],
      "schemas": [
        "Coordonnees"
      ],
      "pageId": 92,
      "hasDocPage": true,
      "concepts": [
        "Identité",
        "Adresse postale",
        "Contact"
      ],
      "starred": false
    },
    {
      "slug": "date-naissance",
      "title": "API Date de Naissance",
      "version": "1.0",
      "description": "L'API Date de Naissance permet d'accéder à l'âge saisi par un individu authentifié sur francetravail.fr. Elle fait partie du dispositif de portabilité des données personnelles.",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-datenaissance/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 1,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/etat-civil",
          "summary": "Récupérer la date de naissance"
        }
      ],
      "schemas": [
        "DateDeNaissance"
      ],
      "pageId": 99,
      "hasDocPage": true,
      "concepts": [
        "Date de naissance"
      ],
      "starred": false
    },
    {
      "slug": "experiences-professionnelles",
      "title": "API Expériences Professionnelles",
      "version": "1.0",
      "description": "Cette API permet d'accéder aux expériences professionnelles saisies par un individu dans son profil de compétences sur francetravail.fr.",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-experiences/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 1,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/experiencesindividu",
          "summary": "Récupérer la liste des expériences professionnelles"
        }
      ],
      "schemas": [
        "Experience"
      ],
      "pageId": 116,
      "hasDocPage": true,
      "concepts": [
        "Intitulé et entreprise",
        "Période et durée",
        "Lieu et contexte"
      ],
      "starred": false
    },
    {
      "slug": "formations-professionnelles",
      "title": "API Formations Professionnelles",
      "version": "1.0",
      "description": "API permettant de récupérer les formations et permis d'un individu depuis son profil de compétences.",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-formations/v1",
      "auth": "peconnect",
      "endpointCount": 2,
      "schemaCount": 2,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/formations",
          "summary": "Lister les formations"
        },
        {
          "method": "GET",
          "path": "/permis",
          "summary": "Lister les permis"
        }
      ],
      "schemas": [
        "Formation",
        "Permis"
      ],
      "pageId": 93,
      "hasDocPage": true,
      "concepts": [
        "Intitulé et diplôme",
        "Niveau et domaine",
        "Permis"
      ],
      "starred": false
    },
    {
      "slug": "metiers-recherches",
      "title": "API PE Connect - Métiers Recherchés",
      "version": "1.0.0",
      "description": "Cette ressource fait remonter les activités professionnelles recherchées (salariées ou non-salariées) par un individu et renseignées au sein du profil de compétences de son espace personnel sur pole-emploi.fr. Deux métiers recherchés du profil au maximum seront remontés par cette API. Le métier…",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-metiersrecherches/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 16,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/metiersrecherches",
          "summary": "Lister les métiers recherchés par un individu"
        }
      ],
      "schemas": [
        "MetierRecherche",
        "Appellation",
        "Contrat",
        "TypeContrat",
        "DureeExperience",
        "UniteExperience",
        "DureeHebdo",
        "TempsTravail",
        "MobiliteHabitation",
        "UniteMobilite",
        "Mobilite",
        "Lieu",
        "TypeLieu",
        "Rome",
        "Salaire",
        "TypologieEmploi"
      ],
      "pageId": 115,
      "hasDocPage": true,
      "concepts": [
        "Métier ROME et appellation",
        "Contrats et temps de travail",
        "Mobilité géographique",
        "Salaire souhaité"
      ],
      "starred": false
    },
    {
      "slug": "statut",
      "title": "API Statut",
      "version": "1.0.0",
      "description": "L’API Statut permet de déterminer si l'utilisateur connecté à votre application est un demandeur d'emploi ou non.",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-statut/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 1,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/statut",
          "summary": "Récupère le statut de l'individu"
        }
      ],
      "schemas": [
        "StatutResponse"
      ],
      "pageId": 135,
      "hasDocPage": true,
      "concepts": [
        "Code statut",
        "Libellé statut"
      ],
      "starred": false
    },
    {
      "slug": "france-travail-connect",
      "title": "France Travail Connect",
      "version": "1.0.0",
      "description": "L'API France Travail Connect permet à un utilisateur (demandeur d'emploi ou candidat) de se connecter à votre application avec son compte France Travail. La solution repose sur la cinématique d'authentification utilisateur proposée par France Travail Access Management. Attention : La licence de…",
      "baseUrl": "api.francetravail.io/partenaire/peconnect-individu/v1",
      "auth": "peconnect",
      "endpointCount": 1,
      "schemaCount": 1,
      "group": "usager-pe",
      "groupLabel": "PE Connect",
      "endpoints": [
        {
          "method": "GET",
          "path": "/userinfo",
          "summary": "Récupérer les informations de l'utilisateur connecté"
        }
      ],
      "schemas": [
        "UserInfo"
      ],
      "pageId": 51,
      "hasDocPage": true,
      "concepts": [
        "Identité",
        "Contact",
        "Identifiants techniques"
      ],
      "starred": false
    },
    {
      "slug": "jcmo-controle-offre",
      "title": "Je Contrôle Mon Offre - JCMO",
      "version": "1",
      "description": "Récupération d'une liste d'appellations métier à partir d'un intitulé et d'un contexte.   Scopes : api_jecontrolemonoffrev1,legaliteoffreemploi   Royaume : /partenaire",
      "baseUrl": "api.francetravail.io/partenaire/jecontrolemonoffre",
      "auth": "public",
      "endpointCount": 1,
      "schemaCount": 4,
      "group": "offres",
      "groupLabel": "Offres d'emploi",
      "endpoints": [
        {
          "method": "POST",
          "path": "/v1/legaliteoffreemploi",
          "summary": "recupererLegaliteOffreEmploi"
        }
      ],
      "schemas": [
        "AlerteDetailList",
        "CriteresLegaliteOffreEmploi",
        "LegaliteOffreEmploi",
        "LegaliteOffreEmpIoi"
      ],
      "pageId": 279,
      "hasDocPage": true,
      "concepts": [
        "Critères de contrôle",
        "Alertes de légalité"
      ],
      "starred": false
    },
    {
      "slug": "offres-emploi",
      "title": "Offres d'emploi",
      "version": "2",
      "description": "Accédez aux offres d'emploi disponibles sur francetravail.fr Consultez les référentiels pour renseigner les critères de recherche d'offres.",
      "baseUrl": "api.francetravail.io/partenaire/offresdemploi",
      "auth": "public",
      "endpointCount": 18,
      "schemaCount": 22,
      "group": "offres",
      "groupLabel": "Offres d'emploi",
      "endpoints": [
        {
          "method": "GET",
          "path": "/v2/offres/search",
          "summary": "Rechercher des offres"
        },
        {
          "method": "GET",
          "path": "/v2/offres/{id}",
          "summary": "Consulter un détail d'offre"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/appellations",
          "summary": "Appellations ROME"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/nafs",
          "summary": "Codes nafs"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/communes",
          "summary": "Communes"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/continents",
          "summary": "Continents"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/departements",
          "summary": "Départements"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/domaines",
          "summary": "Domaines métiers"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/langues",
          "summary": "Langues"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/metiers",
          "summary": "Métiers ROME"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/naturesContrats",
          "summary": "Natures de contrats"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/niveauxFormations",
          "summary": "Niveaux de formations"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/pays",
          "summary": "Pays"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/permis",
          "summary": "Permis"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/regions",
          "summary": "Régions"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/secteursActivites",
          "summary": "Secteurs d'activités"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/themes",
          "summary": "Thèmes"
        },
        {
          "method": "GET",
          "path": "/v2/referentiel/typesContrats",
          "summary": "Types de contrats"
        }
      ],
      "schemas": [
        "Agence",
        "Agregation",
        "Competence",
        "ComplementSalaire",
        "Contact",
        "ContexteTravail",
        "Entreprise",
        "FiltrePossible",
        "Formation",
        "Langue",
        "LieuTravail",
        "Offre",
        "OrigineOffre",
        "PartenaireOffre",
        "Permis",
        "QualitePro",
        "ResultatRecherche",
        "Salaire",
        "Referentiel",
        "Commune",
        "Departement",
        "Region"
      ],
      "pageId": 84,
      "hasDocPage": true,
      "concepts": [
        "Offre d'emploi",
        "Entreprise et lieu",
        "Salaire et conditions",
        "Expérience et compétences"
      ],
      "starred": false
    },
    {
      "slug": "synthese-pages-employeurs",
      "title": "Synthèse des pages employeur",
      "version": "1.0.0",
      "description": "La synthèse pages employeurs restitue des informations synthétiques d'employeurs ayant une page sur France Travail. Grâce à l'API, vous avez la possibilité de filtrer les entreprises que vous souhaitez mettre en avant, selon leurs secteurs d'activité, leurs localisations, date de création, nombre…",
      "baseUrl": "http://api.francetravail.io/partenaire/synthese-pages-employeurs/v1",
      "auth": "public",
      "endpointCount": 4,
      "schemaCount": 25,
      "group": "offres",
      "groupLabel": "Offres d'emploi",
      "endpoints": [
        {
          "method": "GET",
          "path": "/logo-employeur/{idRCE}",
          "summary": "Récupérer le logo d'une entreprise ou d'un établissement pour une page employeur"
        },
        {
          "method": "POST",
          "path": "/page-employeur/recherche",
          "summary": "Rechercher des pages employeurs correspondant aux critères de recherches"
        },
        {
          "method": "POST",
          "path": "/page-employeur/recherche/mise-en-avant",
          "summary": "Rechercher des pages employeurs dans le cadre d'une mise en avant"
        },
        {
          "method": "GET",
          "path": "/widget/image/data/{idImage}",
          "summary": "Récupérer une image avec ses données associées"
        }
      ],
      "schemas": [
        "Adresse",
        "Date",
        "Employeur",
        "Entete",
        "Etablissement",
        "EtablissementContent",
        "ImageNotFound",
        "ImageWidget",
        "InvalidUrlImage",
        "InvalidUrlLogo",
        "LogoNotFound",
        "Page",
        "PageEmployeur",
        "PageEmployeurNotFound",
        "PageEmployeurResult",
        "RecherchePageFailure",
        "RechercheParams",
        "RechercheParams1",
        "RechercheResult",
        "ResultatsOffreNotFound",
        "ResultatsOffreServiceFailure",
        "SinglePageSearchResult",
        "StatutWrapper",
        "TypeLogo",
        "URL"
      ],
      "pageId": 561,
      "hasDocPage": true,
      "concepts": [
        "Pages employeur",
        "Entête et identification",
        "Établissements"
      ],
      "starred": false
    },
    {
      "slug": "rome-4-0-competences",
      "title": "ROME 4.0 - Compétences",
      "version": "1",
      "description": "Référentiel des capacités, ou des ensembles de connaissances, d'aptitudes, d'attitudes et de comportements, qui permettent à une personne d'accomplir une tâche ou de résoudre un problème de manière efficace.Une compétence désigne la capacité à agir dans une situation professionnelle donnée, en…",
      "baseUrl": "api.francetravail.io/partenaire/rome-competences",
      "auth": "public",
      "endpointCount": 21,
      "schemaCount": 12,
      "group": "rome",
      "groupLabel": "ROME 4.0",
      "endpoints": [
        {
          "method": "GET",
          "path": "/v1/competences/categorie-savoirs",
          "summary": "Lister les catégories de savoirs"
        },
        {
          "method": "GET",
          "path": "/v1/competences/categorie-savoirs/{code}",
          "summary": "Lire une catégorie de savoirs"
        },
        {
          "method": "GET",
          "path": "/v1/competences/competence",
          "summary": "Lister les compétences"
        },
        {
          "method": "GET",
          "path": "/v1/competences/competence-detaillee",
          "summary": "Lister les compétences"
        },
        {
          "method": "GET",
          "path": "/v1/competences/competence-detaillee/{code}",
          "summary": "Lire une compétence détaillée"
        },
        {
          "method": "GET",
          "path": "/v1/competences/competence/{code}",
          "summary": "Lire une compétence"
        },
        {
          "method": "GET",
          "path": "/v1/competences/domaine-competence",
          "summary": "Lister les domaines de compétence"
        },
        {
          "method": "GET",
          "path": "/v1/competences/domaine-competence/{code}",
          "summary": "Lire un domaine de compétence"
        },
        {
          "method": "GET",
          "path": "/v1/competences/enjeu",
          "summary": "Lister les enjeux de compétences"
        },
        {
          "method": "GET",
          "path": "/v1/competences/enjeu/{code}",
          "summary": "Lire un enjeu de compétences"
        },
        {
          "method": "GET",
          "path": "/v1/competences/macro-competence",
          "summary": "Lister les macro-compétences"
        },
        {
          "method": "GET",
          "path": "/v1/competences/macro-competence/{code}",
          "summary": "Lire une macro-compétence"
        },
        {
          "method": "GET",
          "path": "/v1/competences/macro-savoir-faire",
          "summary": "Lister les macros savoir-faire"
        },
        {
          "method": "GET",
          "path": "/v1/competences/macro-savoir-faire/{code}",
          "summary": "Lire une macro savoir-faire"
        },
        {
          "method": "GET",
          "path": "/v1/competences/macro-savoir-etre-professionnel",
          "summary": "Lister les macros savoir-être professionnel"
        },
        {
          "method": "GET",
          "path": "/v1/competences/macro-savoir-etre-professionnel/{code}",
          "summary": "Lire une macro savoir-être professionnel"
        },
        {
          "method": "GET",
          "path": "/v1/competences/objectif",
          "summary": "Lister les objectifs"
        },
        {
          "method": "GET",
          "path": "/v1/competences/objectif/{code}",
          "summary": "Lire un objectif"
        },
        {
          "method": "GET",
          "path": "/v1/competences/savoir",
          "summary": "Lister les savoirs"
        },
        {
          "method": "GET",
          "path": "/v1/competences/savoir/{code}",
          "summary": "Lire un savoir"
        },
        {
          "method": "GET",
          "path": "/v1/competences/version",
          "summary": "Récupérer la version actuelle du ROME"
        }
      ],
      "schemas": [
        "CategorieSavoir",
        "Savoir",
        "Competence",
        "CompetenceEsco",
        "CompetenceDetaillee",
        "MacroCompetence",
        "Objectif",
        "Enjeu",
        "DomaineCompetence",
        "MacroSavoirEtreProfessionnel",
        "MacroSavoirFaire",
        "VersionRome"
      ],
      "pageId": 270,
      "hasDocPage": true,
      "concepts": [
        "Compétence et ESCO",
        "Macro-compétence et objectif",
        "Catégorie de savoirs"
      ],
      "starred": false
    },
    {
      "slug": "rome-4-0-fiches-metiers",
      "title": "ROME V4.0 - Fiches ROME",
      "version": "1",
      "description": "L'API « ROME 4.0 - Fiches métiers » permet de structurer les données au format de la fiche ROME.<br/> Cette API vous permet d'identifier, pour chaque fiche :<br/> <ul> <li>Les groupes de compétences mobilisées : les compétences sont classées et ordonnées par enjeu,</li> <li>Les groupes de savoirs :…",
      "baseUrl": "api.francetravail.io/partenaire/rome-fiches-metiers",
      "auth": "public",
      "endpointCount": 3,
      "schemaCount": 12,
      "group": "rome",
      "groupLabel": "ROME 4.0",
      "endpoints": [
        {
          "method": "GET",
          "path": "/v1/fiches-rome/fiche-metier",
          "summary": "Lister les fiches métier"
        },
        {
          "method": "GET",
          "path": "/v1/fiches-rome/fiche-metier/{code}",
          "summary": "Lire une fiche métier"
        },
        {
          "method": "GET",
          "path": "/v1/fiches-rome/version",
          "summary": "Récupérer la version actuelle du ROME"
        }
      ],
      "schemas": [
        "FicheMetier",
        "GroupeCompetences",
        "CompetenceDetaillee",
        "Competence",
        "MacroSavoirEtreProfessionnel",
        "MacroSavoirFaire",
        "Savoir",
        "Enjeu",
        "GroupeSavoirs",
        "CategorieSavoirs",
        "Metier",
        "VersionRome"
      ],
      "pageId": 272,
      "hasDocPage": true,
      "concepts": [
        "Métier",
        "Groupes de compétences",
        "Groupes de savoirs"
      ],
      "starred": false
    },
    {
      "slug": "rome-4-0-contextes-travail",
      "title": "ROME V4.0 - Situations de travail",
      "version": "1",
      "description": "Référentiel des environnements dans lequel une personne exerce son travail.<br/> Le contexte de travail englobe les différents éléments physiques, organisationnels et sociaux qui influencent les tâches, les activités et les interactions professionnelles. Il permet de mieux caractériser l’emploi à…",
      "baseUrl": "api.francetravail.io/partenaire/rome-contextes-travail",
      "auth": "public",
      "endpointCount": 3,
      "schemaCount": 2,
      "group": "rome",
      "groupLabel": "ROME 4.0",
      "endpoints": [
        {
          "method": "GET",
          "path": "/v1/situations-travail/contexte-travail",
          "summary": "Lister les contextes de travail"
        },
        {
          "method": "GET",
          "path": "/v1/situations-travail/contexte-travail/{code}",
          "summary": "Lire un contexte de travail"
        },
        {
          "method": "GET",
          "path": "/v1/situations-travail/version",
          "summary": "Récupérer la version actuelle du ROME"
        }
      ],
      "schemas": [
        "ContexteTravail",
        "VersionRome"
      ],
      "pageId": 271,
      "hasDocPage": true,
      "concepts": [
        "Conditions de travail",
        "Horaires et déplacements",
        "Statut et publics"
      ],
      "starred": false
    },
    {
      "slug": "romeo",
      "title": "Romeo",
      "version": "2.0",
      "description": "Utilisez l’IA afin de vous aider à rapprocher un texte libre à une appellation ou à un savoir / savoir-faire du Répertoire Opérationnel des Métiers et des Emplois (ROME). Scope : api_romeov2 Royaume : /partenaire",
      "baseUrl": "api.francetravail.io/partenaire/romeo/v2",
      "auth": "public",
      "endpointCount": 4,
      "schemaCount": 16,
      "group": "rome",
      "groupLabel": "ROME 4.0",
      "endpoints": [
        {
          "method": "POST",
          "path": "/performancePredictionCompetences",
          "summary": "Renvoyez-nous votre feedback pour permettre l'amélioration du modèle IA"
        },
        {
          "method": "POST",
          "path": "/performancePredictionMetiers",
          "summary": "Renvoyez-nous votre feedback pour permettre l'amélioration du modèle IA"
        },
        {
          "method": "POST",
          "path": "/predictionCompetences",
          "summary": "Prédiction des savoirs / savoir-faire du ROME"
        },
        {
          "method": "POST",
          "path": "/predictionMetiers",
          "summary": "Prédiction des appellations métier du ROME"
        }
      ],
      "schemas": [
        "PerformanceCompetenceDTO",
        "PerformanceCompetence",
        "OptionsSupervision",
        "ExceptionPerformanceCompetence",
        "PerformanceAppellationDTO",
        "PerformanceAppellation",
        "ExceptionPerformanceAppellation",
        "CompetenceDTO",
        "Competence",
        "Options",
        "PredictionCompetence",
        "CompetenceRome",
        "AppellationDTO",
        "Appellation",
        "PredictionAppellation",
        "AppellationRome"
      ],
      "pageId": 366,
      "hasDocPage": true,
      "concepts": [
        "Prédiction métier",
        "Prédiction compétence",
        "Feedback de performance"
      ],
      "starred": false
    },
    {
      "slug": "acces-emploi-demandeurs-emploi",
      "title": "Accès à l'emploi des demandeurs d'emploi",
      "version": "1",
      "description": "Accédez aux statistiques de France Travail - Accès à l'emploi des demandeurs d'emploi.   Cette API présente les taux d'accès à l'emploi à 6 mois des demandeurs d'emploi selon le métier recherché.",
      "baseUrl": "api.francetravail.io/partenaire/stats-perspectives-retour-emploi",
      "auth": "public",
      "endpointCount": 27,
      "schemaCount": 32,
      "group": "stats",
      "groupLabel": "Statistiques",
      "endpoints": [
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-acces-emploi",
          "summary": "Stats d'accès à l'emploi des demandeurs d'emploi catégories A et B (ACC_1)"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activite",
          "summary": "Consulter une activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activites",
          "summary": "Lister les activités"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activites/{codeTypeActivite}",
          "summary": "Lister les activités pour un type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-activites",
          "summary": "Lister les types d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-activite/{codeTypeActivite}",
          "summary": "Consulter un type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristique",
          "summary": "Consulter une caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristiques",
          "summary": "Lister les caractéristiques"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristiques/{codeTypeCaracteristique}",
          "summary": "Lister les caractéristiques par type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-caracteristiques",
          "summary": "Lister les types de caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-caracteristique/{codeTypeCaracteristique}",
          "summary": "Consulter un type de caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/details-indicateurs",
          "summary": "Consulter le détail d'un indicateur."
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclatures",
          "summary": "Lister les nomenclatures"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclatures/{codeTypeNomenclature}",
          "summary": "Lister les nomenclatures par type de nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-nomenclatures",
          "summary": "Lister les types nomenclatures"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclature",
          "summary": "Consulter une nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-nomenclature/{codeTypeNomenclature}",
          "summary": "Consulter un type de nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periodes",
          "summary": "Lister les périodes"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periodes/{codeTypePeriode}",
          "summary": "Lister les périodes par type de période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-periodes",
          "summary": "Lister les types périodes"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periode",
          "summary": "Consulter une période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-periode/{codeTypePeriode}",
          "summary": "Consulter un type de période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires",
          "summary": "Lister les territoires"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires/{codeTypeTerritoire}",
          "summary": "Lister les territoires par type de territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-territoires",
          "summary": "Lister les types de territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoire",
          "summary": "Consulter un territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-territoire/{codeTypeTerritoire}",
          "summary": "Consulter un type de territoire"
        }
      ],
      "schemas": [
        "CritereIndicateurAvecNomenclature",
        "Caracteristique",
        "IndicateurRetour",
        "ValeursParPeriode",
        "ValeursParCaracteristique",
        "Activite",
        "ListeActivite",
        "ListeTypeActivite",
        "TypeActivite",
        "ListeCaracteristique",
        "ListeTypeCaracteristique",
        "TypeCaracteristique",
        "ListeDetailIndicateur",
        "DetailIndicateur",
        "TypeValeur",
        "TypeTerritoire",
        "TypePeriodeIndicateur",
        "TypeNomenclatureIndicateur",
        "ValeurNomenclatureIndicateur",
        "CroisementIndicateur",
        "CaracteristiqueIndicateur",
        "ListeNomenclature",
        "Nomenclature",
        "ListeTypeNomenclature",
        "TypeNomenclature",
        "ListePeriode",
        "Periode",
        "ListeTypePeriode",
        "TypePeriode",
        "ListeTerritoire",
        "Territoire",
        "ListeTypeTerritoire"
      ],
      "pageId": 234,
      "hasDocPage": true,
      "concepts": [
        "Accès emploi demandeurs",
        "Ventilation par caractéristique",
        "Référentiels territoire et activité"
      ],
      "starred": false
    },
    {
      "slug": "marche-travail",
      "title": "Marché du travail",
      "version": "1",
      "description": "Accédez aux statistiques de France Travail - Marché du travail.  Cette API vous fournit toutes les données statistiques essentielles de France Travail pour bien évaluer la situation de l'emploi sur un territoire: chiffres des demandeurs d'emploi, offres, embauches.  Elle intègre des indicateurs…",
      "baseUrl": "api.francetravail.io/partenaire/stats-offres-demandes-emploi",
      "auth": "public",
      "endpointCount": 38,
      "schemaCount": 37,
      "group": "stats",
      "groupLabel": "Statistiques",
      "endpoints": [
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-demandeurs",
          "summary": "Stats des demandeurs d'emploi inscrits en fin de trimestre (DE_1)"
        },
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-demandeurs-entrant",
          "summary": "Stats des demandeurs d'emploi nouveaux inscrits au cours du trimestre et des 12 derniers mois (DE_5)"
        },
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-dynamique-emploi",
          "summary": "Stats sur l'Indicateur global de dynamique de l’emploi sur le territoire sélectionné (DYN_1)"
        },
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-embauches",
          "summary": "Stats sur les embauches (EMB_1)"
        },
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-offres",
          "summary": "Stats sur les offres d'emploi (OFF_1)"
        },
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-perspective-employeur",
          "summary": "Stats sur les difficultés de recrutement (indicateur de tension) (PERSP_2)"
        },
        {
          "method": "GET",
          "path": "/v1/indicateur/salaire-rome-fap/{codeTypeTerritoire}/{codeTerritoire}",
          "summary": "Stats sur les salariés en poste par typologie de salaire (SAL_3)"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activite",
          "summary": "Consulter une activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activites",
          "summary": "Lister les activités"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activites/{codeTypeActivite}",
          "summary": "Lister les activités pour un type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-activites",
          "summary": "Lister les types d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-activite/{codeTypeActivite}",
          "summary": "Consulter un type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristique",
          "summary": "Consulter une caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristiques",
          "summary": "Lister les caractéristiques"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristiques/{codeTypeCaracteristique}",
          "summary": "Lister les caractéristiques par type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-caracteristiques",
          "summary": "Lister les types de caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-caracteristique/{codeTypeCaracteristique}",
          "summary": "Consulter un type de caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/details-indicateurs",
          "summary": "Consulter le détail d'un indicateur."
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/famille-indicateur/{codeFamilleIndicateur}",
          "summary": "Consulter une famille d'indicateur"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/familles-indicateurs",
          "summary": "Lister les familles d'indicateur"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/indicateurs",
          "summary": "Lister les indicateurs"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclatures",
          "summary": "Lister les nomenclatures"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclatures/{codeTypeNomenclature}",
          "summary": "Lister les nomenclatures par type de nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-nomenclatures",
          "summary": "Lister les types nomenclatures"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclature",
          "summary": "Consulter une nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-nomenclature/{codeTypeNomenclature}",
          "summary": "Consulter un type de nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periodes",
          "summary": "Lister les périodes"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periodes/{codeTypePeriode}",
          "summary": "Lister les périodes par type de période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-periodes",
          "summary": "Lister les types périodes"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periode",
          "summary": "Consulter une période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-periode/{codeTypePeriode}",
          "summary": "Consulter un type de période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/rechercherActivitesRomeFap",
          "summary": "Référentiel des correspondances ROME/FAP"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires",
          "summary": "Lister les territoires"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires/{codeTypeTerritoire}",
          "summary": "Lister les territoires par type de territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-territoires",
          "summary": "Lister les types de territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoire",
          "summary": "Consulter un territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires-communes/{codeTypeTerritoire}",
          "summary": "Lister les communes avec Bassin et EPCI"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-territoire/{codeTypeTerritoire}",
          "summary": "Consulter un type de territoire"
        }
      ],
      "schemas": [
        "CritereIndicateurAvecNomenclature",
        "Caracteristique",
        "IndicateurRetour",
        "ValeursParPeriode",
        "ValeursParCaracteristique",
        "CritereIndicateurSansNomenclature",
        "Activite",
        "ListeActivite",
        "ListeTypeActivite",
        "TypeActivite",
        "ListeCaracteristique",
        "ListeTypeCaracteristique",
        "TypeCaracteristique",
        "ListeDetailIndicateur",
        "DetailIndicateur",
        "TypeValeur",
        "TypeTerritoire",
        "TypePeriodeIndicateur",
        "TypeNomenclatureIndicateur",
        "ValeurNomenclatureIndicateur",
        "CroisementIndicateur",
        "CaracteristiqueIndicateur",
        "ListeNomenclature",
        "Nomenclature",
        "ListeTypeNomenclature",
        "TypeNomenclature",
        "ListePeriode",
        "Periode",
        "ListeTypePeriode",
        "TypePeriode",
        "ListeRomeFap",
        "RomeFap",
        "ListeTerritoire",
        "Territoire",
        "ListeTypeTerritoire",
        "ListeTerritoireCommune",
        "TerritoireCommune"
      ],
      "pageId": 233,
      "hasDocPage": true,
      "concepts": [
        "Indicateurs statistiques",
        "Ventilation par caractéristique",
        "Référentiels territoire et activité"
      ],
      "starred": false
    },
    {
      "slug": "sortants-formation-acces-emploi",
      "title": "Sortants de formation et accès à l'emploi",
      "version": "1",
      "description": "Accédez aux statistiques de France Travail - Sortants de formation et accès à l'emploi.  Cette API vous met à disposition des chiffres exacts sur les sorties de formation et l'accès à l'emploi des demandeurs d'emploi en catégories A et B",
      "baseUrl": "api.francetravail.io/partenaire/stats-entrees-sorties-formations",
      "auth": "public",
      "endpointCount": 28,
      "schemaCount": 33,
      "group": "stats",
      "groupLabel": "Statistiques",
      "endpoints": [
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-acces-emploi-sorties-formation",
          "summary": "Stats d'accès à l'emploi des demandeurs d'emploi sortants de formation (ACC_2)"
        },
        {
          "method": "POST",
          "path": "/v1/indicateur/stat-demandeurs-sorties-formation",
          "summary": "Stats des demandeurs d'emploi sortants de formation (DE_3)"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activite",
          "summary": "Consulter une activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activites",
          "summary": "Lister les activités"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/activites/{codeTypeActivite}",
          "summary": "Lister les activités pour un type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-activites",
          "summary": "Lister les types d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-activite/{codeTypeActivite}",
          "summary": "Consulter un type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristique",
          "summary": "Consulter une caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristiques",
          "summary": "Lister les caractéristiques"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/caracteristiques/{codeTypeCaracteristique}",
          "summary": "Lister les caractéristiques par type d'activité"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-caracteristiques",
          "summary": "Lister les types de caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-caracteristique/{codeTypeCaracteristique}",
          "summary": "Consulter un type de caractéristique"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/details-indicateurs",
          "summary": "Consulter le détail d'un indicateur."
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclatures",
          "summary": "Lister les nomenclatures"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclatures/{codeTypeNomenclature}",
          "summary": "Lister les nomenclatures par type de nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-nomenclatures",
          "summary": "Lister les types nomenclatures"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/nomenclature",
          "summary": "Consulter une nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-nomenclature/{codeTypeNomenclature}",
          "summary": "Consulter un type de nomenclature"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periodes",
          "summary": "Lister les périodes"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periodes/{codeTypePeriode}",
          "summary": "Lister les périodes par type de période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-periodes",
          "summary": "Lister les types périodes"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/periode",
          "summary": "Consulter une période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-periode/{codeTypePeriode}",
          "summary": "Consulter un type de période"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires",
          "summary": "Lister les territoires"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoires/{codeTypeTerritoire}",
          "summary": "Lister les territoires par type de territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-territoires",
          "summary": "Lister les types de territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/territoire",
          "summary": "Consulter un territoire"
        },
        {
          "method": "GET",
          "path": "/v1/referentiel/type-territoire/{codeTypeTerritoire}",
          "summary": "Consulter un type de territoire"
        }
      ],
      "schemas": [
        "CritereIndicateurAvecNomenclature",
        "Caracteristique",
        "IndicateurRetour",
        "ValeursParPeriode",
        "ValeursParCaracteristique",
        "CritereIndicateurSansNomenclature",
        "Activite",
        "ListeActivite",
        "ListeTypeActivite",
        "TypeActivite",
        "ListeCaracteristique",
        "ListeTypeCaracteristique",
        "TypeCaracteristique",
        "ListeDetailIndicateur",
        "DetailIndicateur",
        "TypeValeur",
        "TypeTerritoire",
        "TypePeriodeIndicateur",
        "TypeNomenclatureIndicateur",
        "ValeurNomenclatureIndicateur",
        "CroisementIndicateur",
        "CaracteristiqueIndicateur",
        "ListeNomenclature",
        "Nomenclature",
        "ListeTypeNomenclature",
        "TypeNomenclature",
        "ListePeriode",
        "Periode",
        "ListeTypePeriode",
        "TypePeriode",
        "ListeTerritoire",
        "Territoire",
        "ListeTypeTerritoire"
      ],
      "pageId": 231,
      "hasDocPage": true,
      "concepts": [
        "Accès emploi post-formation",
        "Ventilation par caractéristique",
        "Référentiels territoire et activité"
      ],
      "starred": false
    },
    {
      "slug": "prestation-partenaire",
      "title": "Gestion des prestations sous-traitées",
      "version": "1.0.0",
      "description": "Cette API permet à un partenaire authentifié, associé à un marché de prestation (titulaire, cotraitant, ou prestataire), d’accéder à sa programmation et d’en effectuer le suivi.",
      "baseUrl": "api.francetravail.io/partenaire/partenaire-gerer-prestations/v1",
      "auth": "public",
      "endpointCount": 20,
      "schemaCount": 73,
      "group": "partenaire",
      "groupLabel": "Gestion partenaire",
      "endpoints": [
        {
          "method": "GET",
          "path": "/candidature",
          "summary": "Rechercher des candidatures"
        },
        {
          "method": "PUT",
          "path": "/candidature/traitement",
          "summary": "Créer une session et un rendez-vous en base à partir d'une candidature"
        },
        {
          "method": "GET",
          "path": "/candidature/{identifiantCandidature}",
          "summary": "Récupère une candidature à partir de son identifiant"
        },
        {
          "method": "POST",
          "path": "/commande/cloture",
          "summary": "Clôturer une liste de commande"
        },
        {
          "method": "POST",
          "path": "/commande/suspension",
          "summary": "Suspendre une liste de commande"
        },
        {
          "method": "GET",
          "path": "/commande/{numCommande}",
          "summary": "Lire une commande par son numéro de commande"
        },
        {
          "method": "POST",
          "path": "/commande/{numCommande}/soumission-mandataire",
          "summary": "Soumettre une commande au mandataire"
        },
        {
          "method": "GET",
          "path": "/export-commande",
          "summary": "Exporter des commandes"
        },
        {
          "method": "GET",
          "path": "/lieux-realisation/externe",
          "summary": "Rechercher des lieux de réalisation"
        },
        {
          "method": "POST",
          "path": "/pieceGED/ecs",
          "summary": "mettre en ligne un livrable sur ECS"
        },
        {
          "method": "GET",
          "path": "/poste-type-lieu",
          "summary": "Rechercher de type de lieu par poste de marché"
        },
        {
          "method": "GET",
          "path": "/precision-statut-presence",
          "summary": "Rechercher des précisions de statuts de presence"
        },
        {
          "method": "GET",
          "path": "/referentiel-pieceGED",
          "summary": "Rechercher le référentiel des livrables"
        },
        {
          "method": "GET",
          "path": "/resultat",
          "summary": "Recherche les résultats du référentiel"
        },
        {
          "method": "PUT",
          "path": "/rendez-vous/presence/liste",
          "summary": "Modifie une liste de présence d'un rendez-vous"
        },
        {
          "method": "POST",
          "path": "/resultat/rendez-vous/partenaire",
          "summary": "Saisir un resultat d'un rendez-vous depuis un organisme partenaire."
        },
        {
          "method": "GET",
          "path": "/session",
          "summary": "Rechercher des sessions"
        },
        {
          "method": "GET",
          "path": "/session/{identifiantSession}",
          "summary": "Lire session"
        },
        {
          "method": "GET",
          "path": "/sous-precision-resultat",
          "summary": "Rechercher des sous-précisions de résultat"
        },
        {
          "method": "GET",
          "path": "/statut-presence",
          "summary": "Rechercher des statuts de presence"
        }
      ],
      "schemas": [
        "ActiviteCandidature",
        "Adhesion",
        "Adresse",
        "ApercuTypePrestation",
        "Candidature",
        "Commande",
        "Commune",
        "CommuneDa044",
        "Competence",
        "CompetenceCandidature",
        "Connaissance",
        "ConnaissanceCandidature",
        "CoordonneesGPS",
        "Dispositif",
        "DispositifRendezVous",
        "DomaineCompetence",
        "Duree",
        "ElementPrescription",
        "EntreeListeNumeroCommande",
        "EntreeSaisirResultatRendezVous",
        "Entretien",
        "EntretienRendezVous",
        "Etablissement",
        "EvaluationRendezVous",
        "ExportCommande",
        "FamilleMetier",
        "HeaderModeAppelEnum",
        "Individu",
        "InputPart",
        "InputStream",
        "Lien",
        "LieuRealisation",
        "Marche",
        "MediaType",
        "ModificationListeStatutPresence",
        "MotifCandidature",
        "MultivaluedMapStringString",
        "Offre",
        "ParametrageNationalGenICO",
        "ParametrageNationalGenSession",
        "ParametrageSession",
        "PeriodeMarche",
        "PieceGED",
        "Poste",
        "PosteTypeLieu",
        "PrecisionResultat",
        "PrecisionStatutPresence",
        "Prestataire",
        "PrestationSpecifique",
        "Question",
        "ReferentielPieceGED",
        "ReferentielStatutMetierPresta",
        "Relance",
        "RendezVous",
        "Reponse",
        "ReponseDefinie",
        "Resultat",
        "ResultatRendezVous",
        "Rome",
        "SaisirResultatRendezVous",
        "Session",
        "Site",
        "SousPrecisionResultat",
        "SousThemeAtelier",
        "StatutCommandeReferentiel",
        "StatutMetierPresta",
        "StatutPresence",
        "ThemeAtelier",
        "TraitementCandidature",
        "TypeLivrable",
        "TypePrestataire",
        "TypePrestation",
        "TypePublic"
      ],
      "pageId": 260,
      "hasDocPage": true,
      "concepts": [
        "Candidatures",
        "Sessions et programmation",
        "Commandes",
        "Rendez-vous et présence",
        "Résultats et livrables"
      ],
      "starred": true
    },
    {
      "slug": "gestion-sanctions-rsa",
      "title": "Gestion des sanctions RSA",
      "version": "1.1",
      "description": "Cette API met à disposition les propositions sur les sanctions des bénéficiaires du RSA accompagnés par France Travail, afin de statuer sur ces dernières propositions. <br>Elle permet également de transmettre des décisions de sanctions RSA pour un bénéficiaire RSA non accompagné par France Travail…",
      "baseUrl": "api.francetravail.io/partenaire/gestion-sanctions-rsa/v1",
      "auth": "agent",
      "endpointCount": 4,
      "schemaCount": 17,
      "group": "partenaire",
      "groupLabel": "Gestion partenaire",
      "endpoints": [
        {
          "method": "GET",
          "path": "/detailManquement",
          "summary": "Restituer le détail d'un manquement"
        },
        {
          "method": "POST",
          "path": "/evenementSanctionRSA",
          "summary": "Transmettre un événement sur une conséquence de sanction RSA"
        },
        {
          "method": "POST",
          "path": "/decisionSanctionRSAPartenaire",
          "summary": "Transmettre une décision de sanction RSA pour un bRSA accompagné par un partenaire"
        },
        {
          "method": "POST",
          "path": "/demandeRadiation",
          "summary": "Transmettre une demande de radiation de la liste des DE pour un bRSA"
        }
      ],
      "schemas": [
        "DetailManquement",
        "Individu",
        "FaisceauIndice",
        "DetailAttribut",
        "DetailSanction",
        "DetailEvenementSanction",
        "ErreurDetailManquement",
        "TraitementSanctionRsa",
        "Evenement",
        "RetourTraitementRsaOTD",
        "ErreurTraitementSanctionRsa",
        "DecisionSanctionRsa",
        "RetourDecisionSanctionRSA",
        "ErreurDecisionSanctionRsa",
        "DemandeRadiation",
        "RetourDemandeRadiation",
        "ErreurDemandeRadiation"
      ],
      "pageId": 497,
      "hasDocPage": true,
      "concepts": [
        "Manquement — fait reproché",
        "Conséquences de sanction",
        "Événements de traitement"
      ],
      "starred": false
    },
    {
      "slug": "evenements-france-travail",
      "title": "API Mes évènements emplois",
      "version": "1.0.0",
      "description": "Cette API permet de rechercher et récupérer des informations sur les événements emploi, salons en ligne et ateliers organisés par France Travail et ses partenaires.",
      "baseUrl": "api.francetravail.io/partenaire/evenements/v1",
      "auth": "public",
      "endpointCount": 5,
      "schemaCount": 6,
      "group": "standalone",
      "groupLabel": "Services",
      "endpoints": [
        {
          "method": "GET",
          "path": "/salonsenligne",
          "summary": "Rechercher les salons en ligne en cours et à venir"
        },
        {
          "method": "GET",
          "path": "/salonsenligne/jeunes",
          "summary": "Rechercher les salons ciblés 'Jeunes' en cours et à venir"
        },
        {
          "method": "POST",
          "path": "/mee/evenements",
          "summary": "Rechercher les événements \"Mes événements emploi\""
        },
        {
          "method": "GET",
          "path": "/mee/evenement/{evenement_id}",
          "summary": "Rechercher détail d'un événement"
        },
        {
          "method": "GET",
          "path": "/mee/tags/opera/lister",
          "summary": "Référentiel opérations"
        }
      ],
      "schemas": [
        "SalonEnLigne",
        "EvenementRequest",
        "EvenementResponse",
        "Evenement",
        "EvenementDetail",
        "Operation"
      ],
      "pageId": 103,
      "hasDocPage": true,
      "concepts": [
        "Salons en ligne",
        "Événements emploi",
        "Publics et objectifs"
      ],
      "starred": false
    },
    {
      "slug": "referentiel-agences",
      "title": "API Référentiel des Agences",
      "version": "1.0.0",
      "description": "Cette API permet de trouver les agences et points relais France Travail en France (métropole et DROM).",
      "baseUrl": "api.francetravail.io/partenaire/referentielagences/v1",
      "auth": "public",
      "endpointCount": 2,
      "schemaCount": 1,
      "group": "standalone",
      "groupLabel": "Services",
      "endpoints": [
        {
          "method": "GET",
          "path": "/agences",
          "summary": "Rechercher des agences"
        },
        {
          "method": "GET",
          "path": "/agences/{code}",
          "summary": "Consulter les détails d'une agence"
        }
      ],
      "schemas": [
        "Agence"
      ],
      "pageId": 107,
      "hasDocPage": true,
      "concepts": [
        "Identité et type",
        "Adresse et localisation",
        "Horaires d'ouverture"
      ],
      "starred": false
    }
  ],
  "groups": [
    {
      "id": "usager-agent",
      "label": "Dossier usager",
      "description": "APIs agent pour accéder au dossier complet d'un demandeur d'emploi"
    },
    {
      "id": "usager-pe",
      "label": "PE Connect",
      "description": "APIs usager via France Travail Connect (OAuth individu)"
    },
    {
      "id": "offres",
      "label": "Offres d'emploi",
      "description": "Recherche d'offres, contrôle, pages employeur"
    },
    {
      "id": "rome",
      "label": "ROME 4.0",
      "description": "Classification des métiers et compétences"
    },
    {
      "id": "stats",
      "label": "Statistiques",
      "description": "Indicateurs marché du travail, accès emploi, formation"
    },
    {
      "id": "partenaire",
      "label": "Gestion partenaire",
      "description": "Prestations sous-traitées, sanctions RSA"
    },
    {
      "id": "standalone",
      "label": "Services",
      "description": "Référentiels et événements"
    }
  ],
  "crossConcepts": [
    {
      "name": "Niveau d'étude",
      "apis": [
        "orientation-usager",
        "formations-professionnelles",
        "offres-emploi"
      ],
      "collision": false,
      "shared": true,
      "description": "10 codes strictement identiques entre APIs : AFS · CP4 · CFG · C3A · C12 · NV5 · NV4 · NV3 · NV2 · NV1 (du plus faible au plus élevé). Référentiel canonique servi par offres-emploi."
    },
    {
      "name": "Organismes du réseau pour l'emploi",
      "apis": [
        "orientation-usager",
        "rendez-vous-partenaires",
        "gestion-sanctions-rsa"
      ],
      "collision": false,
      "shared": true,
      "description": "Codes FT (France Travail) · CD (Conseil départemental) · CAF · ML (Mission locale) · CE (Cap emploi) · IND (Indéterminé). Variations mineures selon le cas d'usage : RDV-partenaires ajoute DCD (délégation CD) et omet CAF ; la décision d'orientation exclut IND."
    },
    {
      "name": "Freins à l'emploi (8 dimensions)",
      "apis": [
        "diagnostic-usager",
        "orientation-usager"
      ],
      "collision": false,
      "shared": true,
      "description": "Les mêmes 8 dimensions partagées entre les deux APIs : santé · logement · mobilité · famille · finances · numérique · administratif-juridique · français-calcul. Orientation expose un résumé (impact fort / faible / aucun) ; Diagnostic expose le détail (situations constatées + objectifs). C'est la vue grosse maille vs la vue fine maille du même sujet."
    },
    {
      "name": "Usager / Individu",
      "apis": [
        "france-travail-connect",
        "coordonnees",
        "informations-administratives-usager",
        "rechercher-usager",
        "gestion-sanctions-rsa",
        "prestation-partenaire",
        "date-naissance",
        "statut-usager"
      ],
      "collision": true
    },
    {
      "name": "Code ROME",
      "apis": [
        "rome-4-0-fiches-metiers",
        "rome-4-0-competences",
        "romeo",
        "offres-emploi",
        "metiers-recherches",
        "metiers-recherches-projets-evolution",
        "diagnostic-usager",
        "evenements-france-travail",
        "prestation-partenaire",
        "rome-4-0-contextes-travail"
      ],
      "collision": false
    },
    {
      "name": "Compétence",
      "apis": [
        "rome-4-0-competences",
        "rome-4-0-fiches-metiers",
        "romeo",
        "offres-emploi",
        "ajout-competence"
      ],
      "collision": true
    },
    {
      "name": "Adresse",
      "apis": [
        "coordonnees",
        "informations-administratives-usager",
        "referentiel-agences",
        "offres-emploi",
        "metiers-recherches-projets-evolution",
        "evenements-france-travail",
        "synthese-pages-employeurs",
        "prestation-partenaire",
        "rendez-vous-partenaires"
      ],
      "collision": true
    },
    {
      "name": "Agent / Conseiller",
      "apis": [
        "diagnostic-usager",
        "conclusions-entretiens",
        "rechercher-usager",
        "rendez-vous-partenaires",
        "prestation-partenaire"
      ],
      "collision": false
    },
    {
      "name": "Contrat",
      "apis": [
        "metiers-recherches-projets-evolution",
        "metiers-recherches",
        "offres-emploi",
        "statut-usager"
      ],
      "collision": false
    },
    {
      "name": "Agence / Structure",
      "apis": [
        "referentiel-agences",
        "conclusions-entretiens",
        "diagnostic-usager",
        "rendez-vous-partenaires",
        "prestation-partenaire"
      ],
      "collision": false
    },
    {
      "name": "Rendez-vous",
      "apis": [
        "rendez-vous-partenaires",
        "conclusions-entretiens",
        "prestation-partenaire"
      ],
      "collision": false
    },
    {
      "name": "Statut",
      "apis": [
        "statut",
        "statut-usager",
        "diagnostic-usager",
        "prestation-partenaire"
      ],
      "collision": true
    },
    {
      "name": "Salaire",
      "apis": [
        "offres-emploi",
        "metiers-recherches-projets-evolution",
        "metiers-recherches",
        "marche-travail"
      ],
      "collision": true
    },
    {
      "name": "Permis",
      "apis": [
        "formations-professionnelles",
        "offres-emploi",
        "diagnostic-usager"
      ],
      "collision": true
    },
    {
      "name": "Formation",
      "apis": [
        "formations-professionnelles",
        "offres-emploi",
        "evenements-france-travail"
      ],
      "collision": true
    }
  ],
  "starred": [
    "diagnostic-usager",
    "orientation-usager",
    "rendez-vous-partenaires",
    "prestation-partenaire"
  ]
};
